version: '3.7'
services:
  redpanda0:
    # NOTE: Please use the latest version here!
    image: docker.redpanda.com/vectorized/redpanda:v22.1.4
    container_name: redpanda-0
    command:
    - redpanda
    - start
    - --smp
    - '1'
    - --reserve-memory
    - 0M
    - --overprovisioned
    - --node-id
    - '0'
    - --kafka-addr
    - PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
    - --advertise-kafka-addr
    - PLAINTEXT://redpanda-0:29092,OUTSIDE://localhost:9092
    - --pandaproxy-addr
    - PLAINTEXT://0.0.0.0:28082,OUTSIDE://0.0.0.0:8082
    - --advertise-pandaproxy-addr
    - PLAINTEXT://redpanda-0:28082,OUTSIDE://localhost:8082
    - --rpc-addr 0.0.0.0:33145 
    - --advertise-rpc-addr redpanda-0:33145
    ports:
    - 8081:8081
    - 8082:8082
    - 9092:9092
    - 28082:28082
  redpanda1:
    # NOTE: Please use the latest version here!
    image: docker.redpanda.com/vectorized/redpanda:v22.1.4
    container_name: redpanda-1
    command:
    - redpanda
    - start
    - --smp
    - '1'
    - --reserve-memory
    - 0M
    - --overprovisioned
    - --node-id
    - '1'
    - --seeds 
    - redpanda-0:33145
    - --kafka-addr
    - PLAINTEXT://0.0.0.0:29093,OUTSIDE://0.0.0.0:9093
    - --advertise-kafka-addr
    - PLAINTEXT://redpanda-1:29093,OUTSIDE://localhost:9093
    - --pandaproxy-addr
    - PLAINTEXT://0.0.0.0:28083,OUTSIDE://0.0.0.0:8083
    - --advertise-pandaproxy-addr
    - PLAINTEXT://redpanda-1:28083,OUTSIDE://localhost:8083
    - --rpc-addr 0.0.0.0:33146
    - --advertise-rpc-addr redpanda-1:33146
    ports:
    - 8083:8083
    - 9093:9093
  redpanda2:
    # NOTE: Please use the latest version here!
    image: docker.redpanda.com/vectorized/redpanda:v22.1.4
    container_name: redpanda-2
    command:
    - redpanda
    - start
    - --smp
    - '1'
    - --reserve-memory
    - 0M
    - --overprovisioned
    - --node-id
    - '2'
    - --seeds
    - redpanda-0:33145
    - --kafka-addr
    - PLAINTEXT://0.0.0.0:29094,OUTSIDE://0.0.0.0:9094
    - --advertise-kafka-addr
    - PLAINTEXT://redpanda-2:29094,OUTSIDE://localhost:9094
    - --pandaproxy-addr
    - PLAINTEXT://0.0.0.0:28084,OUTSIDE://0.0.0.0:8084
    - --advertise-pandaproxy-addr
    - PLAINTEXT://redpanda-2:28084,OUTSIDE://localhost:8084
    - --rpc-addr 0.0.0.0:33147
    - --advertise-rpc-addr redpanda-2:33147
    ports:
    - 8084:8084
    - 9094:9094
  console:
    image: docker.redpanda.com/vectorized/console:master-0a8fce8
    container_name: console
    environment:
      - "KAFKA_BROKERS=redpanda-0:29092,redpanda-1:29093,redpanda-2:29094"
    ports:
    - 8080:8080
  grafana:
    image: grafana/grafana
    container_name: grafana
    environment:
      - "GF_AUTH_ANONYMOUS_ENABLED=true"
      - "GF_AUTH_ANONYMOUS_ORG_ROLE=Admin"
      - "GF_AUTH_ANONYMOUS_HIDE_VERSION=true"
    volumes:
      # Mount provisioning configuration
      - "./config/grafana/provisioning:/etc/grafana/provisioning"
      # Mount dashboards
      - "../grafana-dashboards:/var/lib/grafana/dashboards"
    ports: [ "3000:3000" ]
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    # Mount prometheus configuration
    volumes: [ "./config/prometheus.yml:/etc/prometheus/prometheus.yml" ]
    ports: [ "9090:9090" ]
